[theme]
primaryColor = "#6c63ff"                  # Button color
backgroundColor = "#ffffff"              # Main background
secondaryBackgroundColor = "#f0f2f6"     # Sidebar and widgets
textColor = "#000000"                    # Text color
font = "sans serif"                      # Font type (options: sans serif, serif, monospace)

[server]
headless = true
enableCORS = false
port = 8501

[client]
showSidebarNavigation = true

[ui]
hideTopBar = false
